---
title: "t47d_pca_traj"
output: html_document
date: "2024-02-14"
---

```{r, include=FALSE}
library(Seurat)
library(grid)
library(slingshot)
library(dplyr)
library(scater)
library(tidyverse)
library(scatterplot3d)
library(plotly)
library(ggplot2)
```


```{r}
#adjust file location if necessary
df = read.csv("data/T47D_PCA.csv")
```

```{r}
#first we make a SCE object of all the data in order to plot the curves atop the PCA
big = subset(df)
cols = c('AreaShape_Area', 'Intensity_IntegratedIntensity_DNA', 'Intensity_MedianIntensity_CDK2', 'Intensity_MedianIntensity_CDK4', 'Intensity_MedianIntensity_CDK6', 'Intensity_MedianIntensity_Cdh1', 'Intensity_MedianIntensity_Cdt1', 'Intensity_MedianIntensity_E2F1', 'Intensity_MedianIntensity_ER', 'Intensity_MedianIntensity_Ki67', 'Intensity_MedianIntensity_PR', 'Intensity_MedianIntensity_RB', 'Intensity_MedianIntensity_Skp2', 'Intensity_MedianIntensity_cycA', 'Intensity_MedianIntensity_cycB1', 'Intensity_MedianIntensity_cycD1', 'Intensity_MedianIntensity_cycE', 'Intensity_MedianIntensity_p21', 'Intensity_MedianIntensity_pRB', 'pRB_over_RB')
raw_df_big = subset(big, select=cols)

pca_plot = subset(big, select=c(PCA_1, PCA_2, PCA_3))
sce_big <- SingleCellExperiment(t(raw_df_big))
colData(sce_big)$phase = big$phase

reducedDims(sce_big) <- list(PCA=as.matrix(pca_plot))
#we dont use the trajectories found here, this is just for plotting

#this function finds trajectories 
trj <- function(data, sce_want) {
      #subset to the features, not using the metadata
      raw_df = subset(data, select=cols)
      #pca coordinates - we use three dimensions
      pca = subset(data, select=c(PCA_1, PCA_2, PCA_3))
      #create SCE object
      sce <- SingleCellExperiment(assays = as.matrix(t(raw_df)))
      colData(sce)$phase = data$phase
      
      reducedDims(sce) <- list(PCA=as.matrix(pca))
      #run Slingshot, only giving starting cluster of G0
      sce <- slingshot(
              sce,
              reducedDim = 'PCA',
              clusterLabels = 'phase',
              start.clus = 'G0', allow.breaks=F
      )
      slo <- SlingshotDataSet(sce)
      if (sce_want==T) {return(sce)} #if you want SCE object or Slingshot object to be returned
      else {return(slo)} 
}

#first we just run to get the curve coordinates, so we want a Slingshot object
untrt = subset(df, df$metadata_well==0)
sce_untrt = trj(untrt, sce_want=T)
slo_untrt = trj(untrt, sce_want=F)

one = subset(df, df$metadata_well==1)
slo_one = trj(one, sce_want=F)
sce_one = trj(one, sce_want=T)

ten = subset(df, df$metadata_well==10)
slo_ten = trj(ten, sce_want=F)
sce_ten = trj(ten, sce_want=T)

hundo = subset(df, df$metadata_well==100)
slo_hundo = trj(hundo, sce_want=F)
sce_hundo = trj(hundo, sce_want=T)

onek = subset(df, df$metadata_well==1000)
slo_onek = trj(onek, sce_want=F)
sce_onek = trj(onek, sce_want=T)


##plot lineages together - untrt as dashed line, trt as solid
curve_untrt = slingCurves(slo_untrt, as.df = TRUE) %>%
      dplyr::rename("X" = "PCA_1", "Y" = "PCA_2", "Z" = "PCA_3")
print(curve_untrt)
curve_one = slingCurves(slo_one, as.df = TRUE) %>%
      dplyr::rename("X" = "PCA_1", "Y" = "PCA_2", "Z" = "PCA_3")
curve_ten = slingCurves(slo_ten, as.df = TRUE) %>%
      dplyr::rename("X" = "PCA_1", "Y" = "PCA_2", "Z" = "PCA_3")
curve_hundo = slingCurves(slo_hundo, as.df = TRUE) %>%
      dplyr::rename("X" = "PCA_1", "Y" = "PCA_2", "Z" = "PCA_3")
curve_onek = slingCurves(slo_onek, as.df = TRUE) %>%
      dplyr::rename("X" = "PCA_1", "Y" = "PCA_2", "Z" = "PCA_3")

#subset to lineages we want - look at them to confirm
slo_untrt@lineages
slo_one@lineages
slo_ten@lineages
slo_hundo@lineages
slo_onek@lineages

curve_untrt = subset(curve_untrt, curve_untrt$Lineage == 1)
curve_one = subset(curve_one, curve_one$Lineage == 1)
curve_ten = subset(curve_ten, curve_ten$Lineage == 1)
curve_hundo = subset(curve_hundo, curve_hundo$Lineage == 1)
curve_onek = subset(curve_onek, curve_onek$Lineage == 1)

# save curve coords to csv
curve_x <- c(curve_untrt$X, curve_one$X, curve_ten$X, curve_hundo$X, curve_onek$X)
curve_y <- c(curve_untrt$Y, curve_one$Y, curve_ten$Y, curve_hundo$Y, curve_onek$Y)
curve_z <- c(curve_untrt$Z, curve_one$Z, curve_ten$Z, curve_hundo$Z, curve_onek$Z)
slingshot_xyz <- data.frame(curve_x, curve_y, curve_z)
print(slingshot_xyz)

write.csv(slingshot_xyz, "/Users/oliviawen/singlecell_spca/data/T47D_PCA_Curves.csv", row.names=FALSE)

print(sce_untrt$slingPseudotime_1)

# save pseudotimes to csv 
untrt_pseudotime = slingPseudotime(slo_untrt)
one_pseudotime = slingPseudotime(slo_one)
ten_pseudotime = slingPseudotime(slo_ten)
hundo_pseudotime = slingPseudotime(slo_hundo)
onek_pseudotime = slingPseudotime(slo_onek)

pseudotimes_all <- data.frame(c(untrt_pseudotime, one_pseudotime, ten_pseudotime, hundo_pseudotime, onek_pseudotime))
colnames(pseudotimes_all) <- "pseudotime"
print(pseudotimes_all)

# add pseudotimes as column in df
untrt$pseudotime <- sce_untrt$slingPseudotime_1
one$pseudotime <- sce_one$slingPseudotime_1
ten$pseudotime <- sce_ten$slingPseudotime_1
hundo$pseudotime <- sce_hundo$slingPseudotime_1
onek$pseudotime <- sce_onek$slingPseudotime_1

write.csv(pseudotimes_all, "/Users/oliviawen/singlecell_spca/data/T47D_PCA_Pseudotimes.csv", row.names=FALSE)
```